title = "TITLE OF CONFERENCE"
baseURL = "https://lizziemickiewicz.github.io/" #CHANGE URL
theme = "researcher"
enableEmoji = true

math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "roundtable2027" #CHANGE AUTHOR
  description = "roundtable2027"
  favicon = "" #CHANGE ICON
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "made with © SOMEONE"
    url = "https://github.com/lizziemickiewicz/lizziemickiewicz.github.io/" #CHANGE URL
  [params.style]
    fontFamily = "sans-serif"
    pageWidth = "1200px"
    avatarSize = "185px"
    colorBlack = "white"
    colorRed = "#afdcff"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "Email"
    url = "" #CHANGE EMAIL

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
[[menu.main]]
    name = "KEYNOTE SPEAKERS"
    url = "/keynotespeakers"
    weight = 2
[[menu.main]]
    name = "PROGRAM"
    url = "/program"
    weight = 3
  [[menu.main]]
    name = "TRAVEL"
    url = "/travel"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files